### ISSUE TITLE
Install gdb in the Intel containers

### ISSUE THREAD

**Issue by rhoneyager** [JCSDA/charliecloud#36]
The Intel containers do not have gdb installed. This is problematic because we cannot debug.

I've hit a situation in JCSDA/ioda-engines#76 where I am encountering a segfault that only occurs inside the Intel containers.

**Comment by mmiesch** [comment]
What container are you using?  If Docker or Singularity you can install gdb yourself for debugging.  I'd have to check for Charliecloud.

**Comment by mmiesch** [comment]
I'm not sure why it's not there - intel PS comes with it and it wasn't deliberately removed.  It will take some investigation next week.  But, as I said, if you use docker or singularity you can install the gnu version on your own for debugging purposes.  Let me know which you want to work with and I can give you further info.

**Comment by rhoneyager** [comment]
Unfortunately, Charliecloud.

I'll spin up a Docker container in the meantime.

**Comment by mmiesch** [comment]
Strange - I had mentioned before about a bug in the install of intel 19/20 parallel studio  where it was ignoring the component list.  Apparently it's not completely ignoring it.  This is fixed - I'm just regenerating the containers now - will be done within the hour.

**Comment by mmiesch** [comment]
@rhoneyager - Ok, the latest intel 19 docker, singularity, and charliecloud containers on AWS S3 should be updated with the the intel version of gdb, `gdb-ia`.   I have not tested these yet - please let me know if you notice a problem.  @mer-a-o - there is no need to change the container on AWS for CI because the only change should be this, which is not needed for CI.
